name: VRT by Playwright

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  vrt-by-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Compose build
        run: docker compose build

      - name: Run playwright with yarn vrt
        run: docker compose run -e API_BASE_URL=${{ secrets.API_BASE_URL }} -e API_KEY=${{ secrets.API_KEY }} -e APP_URL=${{ secrets.APP_URL }} playwright yarn vrt
